## cachematrix: Functions to cache the inversion of a matrix.
##
## These functions allow you to cache the inversion of a matrix,
## using a specially-designed List object.
##
## Usage:
##   c <- makeCacheMatrix(m)  ## Where "m" is a matrix
##   s <- cacheSolve(c)       ## Where "c" is a CacheMatrix object
##
## s will then contain the result of solve(m).  Subsequent calls to
## the cacheSolve(c) function will return the result of solve(m),
## but without the overhead of recalculating the inverse.

## makeCacheMatrix: Make a new "caching matrix" object.  The object
## provides four functions, which are described below:
##
##   set(y)      -- Set the underlying matrix to "y"
##   get()       -- Get the underlying (non-inverted) matrix
##   setinv(inv) -- Set the cached/inverted matrix to "inv"
##   getinv()    -- Get the cached/inverted matrix
##
## Note that the cached matrix must be "setinv" before it can be "getinv".
## This means that the actual work of solving must be done elsewhere!
##
## If there is no underlying matrix or no cached matrix, the respective
## "get" functions will return NULL.

makeCacheMatrix <- function(x = matrix()) {
  # The cached matrix (NULL by default)
  i <- NULL
  # Set: stores the original matrix in x and resets the inverse
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  # Get: returns the original (non-inverse) matrix previously stored
  get <- function() x
  # Setinv: stores the inverse matrix (calculated elsewhere)
  setinv <- function(inv) i <<- inv
  # Getinv: returns the inverse matrix previously stored
  getinv <- function() i
  # Create a list of the above functions; this is the "object"
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## cacheSolve: calculate the inverse of a CacheMatrix, or return the
## cached inverse if it has already been calculated.  The parameter
## must be a CacheMatrix as generated by makeCacheMatrix.

cacheSolve <- function(x, ...) {
  # Get the cached inverse
  i <- x$getinv()
  # If it's not NULL, it's was calculated already!
  if (!is.null(i)) {
    message("Getting cached data")
    return(i)
  }
  # If we don't have it cached, retrieve the data and solve it
  message("Calculating and caching data")
  data <- x$get()
  i <- solve(data, ...)
  # Now that we solved, set it in the CacheMatrix object and return the inverse
  x$setinv(i)
  i
}
